language: java
jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
  - master
  - development

notifications:
  slack: csseg7:SbU27bN9RRyw3zL3kWOncXnz

services: mongodb

before-script:
  - sleep 15
  - mongo analytics_data --eval 'db.createUser({ user: "root", pwd: "root", roles: [{ role: "readWrite", db: "analytics_data" }]});'
